INDEX



<article class="col1 pad_right1">
    <h2><strong class="color1">Small</strong><span>$9.95/month</span></h2>
    <ul class="list1">
        <li><span>300 GB</span>Disk space</li>
        <li><span>3000 GB</span>Monthly data transfer</li>
        <li><span>25</span>FTP accounts</li>
        <li><span>1000</span>Email boxes</li>
        <li class="end"><span>1</span>Free domains</li>
    </ul>
    <div class="button_details">
        <a href="#" class="color1">Details</a>
    </div>
</article>
<article class="col1 pad_right1">
    <h2><strong class="color2">Medium</strong><span>$14.95/month</span></h2>
    <ul class="list1">
        <li><span>500 GB</span>Disk space</li>
        <li><span>5000 GB</span>Monthly data transfer</li>
        <li><span>50</span>FTP accounts</li>
        <li><span>1000</span>Email boxes</li>
        <li class="end"><span>1</span>Free domains</li>
    </ul>
    <div class="button_details">
        <a href="#" class="color2">Details</a>
    </div>
</article>
<article class="col1">
    <h2><strong>Unlimited</strong><span>$19.95/month</span></h2>
    <ul class="list1">
        <li><span>Unlimited</span>Disk space</li>
        <li><span>Unlimited</span>Monthly data transfer</li>
        <li><span>Unlimited</span>FTP accounts</li>
        <li><span>Unlimited</span>Email boxes</li>
        <li class="end"><span>3</span>Free domains</li>
    </ul>
    <div class="button_details">
        <a href="#">Details</a>
    </div>
</article>


<div class="body3">
    <div class="main">
        <section id="content2">
            <div class="line2 wrapper">
                <article class="col2 pad_right1">
                    <h3>Register Domain Name</h3>
                    <form id="form_1" method="post">
                        <div>
                            <div class="wrapper">
                                <div class="col1">
                                    <input type="text" class="input" value="Type domain name here" onblur="if(this.value=='') this.value='Type domain name here'" onFocus="if(this.value =='Type domain name here' ) this.value=''">
                                </div>
                                <div class="col2">
                                    <div class="row">
                                        <input type="checkbox">.net
                                    </div>
                                    <div class="row">
                                        <input type="checkbox">.info
                                    </div>
                                    <div class="row">
                                        <input type="checkbox">.co.uk
                                    </div>
                                    <div class="row">
                                        <input type="checkbox">.mx
                                    </div>
                                </div>
                                <div class="col2">
                                    <div class="row">
                                        <input type="checkbox">.com
                                    </div>
                                    <div class="row">
                                        <input type="checkbox">.mobi
                                    </div>
                                    <div class="row">
                                        <input type="checkbox">.eu
                                    </div>
                                    <div class="row">
                                        <input type="checkbox">.us
                                    </div>
                                </div>
                                <div class="col2">
                                    <div class="row">
                                        <input type="checkbox">.net
                                    </div>
                                    <div class="row">
                                        <input type="checkbox">.info
                                    </div>
                                    <div class="row">
                                        <input type="checkbox">.co.uk
                                    </div>
                                    <div class="row">
                                        <input type="checkbox">.mx
                                    </div>
                                </div>
                                <div class="col2">
                                    <div class="row">
                                        <input type="checkbox">.com
                                    </div>
                                    <div class="row">
                                        <input type="checkbox">.mobi
                                    </div>
                                    <div class="row">
                                        <input type="checkbox">.eu
                                    </div>
                                    <div class="row">
                                        <input type="checkbox">.us
                                    </div>
                                </div>
                            </div>
                            <div class="wrapper">
                                <span class="links"><a href="#">Renew a domain</a> &nbsp; l &nbsp; <a href="#">Transfer a domain</a> &nbsp;l&nbsp; <a href="#">WHOIS</a></span>
                                <a href="#" class="button1" onClick="document.getElementById('form_1').submit()">Check Domain</a>
                            </div>
                        </div>
                    </form>
                </article>
                <article class="col1">
                    <h3>Get Started!</h3>
                    <p class="pad_bot1">
                        <strong class="color3">Don't have hosting website yet?</strong><br>
                        Let us help you get started offer you this theme - one of <a href="http://blog.templatemonster.com/free-website-templates/" target="_blank">free
                            website tem- plates</a> created by TemplateMonster.<br>com. This template goes with two
                        packages – with PSD source files and without them. PSD source files are available for free
                        for the registered members of TemplateMonster.com.
                    </p>
                </article>
            </div>
        </section>
        <!-- / content  -->
    </div>
</div>



LOGIN-----------------------------------------


<section id="content">
    <div class="wrapper">
        <article class="col3">
            <h3>Our Promise</h3>
            <p><strong class="color3">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                    exercitation ullamco laboris nisi.</strong></p>
            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,
                totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae
                dicta sunt explicabo.</p>
            <p class="pad_bot1"><strong class="color3">We Promise:</strong></p>
            <ul class="list4 pad_bot2">
                <li><span>To be accessible, friendly, and helpful at all times.</span></li>
                <li><span>To answer the phone when you call, 24/7/365.</span></li>
                <li><span>Reply to your emails and support tickets within 24 hours.</span></li>
                <li><span>To provide timely information regarding System Incidents.</span></li>
                <li><span>And lastly, we promise to listen.</span></li>
            </ul>
            <p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur
                magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem
                ipsum quia dolor sit amet, consectetur, adipisci velit.</p>
        </article>
    </div>
</section>



REGISTRO----------------------------------------------------------------------
<section id="content">
    <div class="wrapper">
        <article class="col3">
            <h3>A Few Words About Us</h3>
            <figure class="left marg_right1"><img src="images/page4_img1.jpg" alt=""></figure>
            <p>Vivamus non velit in nibh tincidunt tristique tincidunt in leo. Phasellus eget nulla odio.
                Maecenas at gravida lorem. Integer imperdiet euismod neque quis luctus. Donec facilisis lobortis
                viverra. Quisque vehicula suscipit posuere. Nam non lacus dui, gravida condimentum tortor.
                Maecenas ultrices volutpat euismod. Nam pellentesque imperdiet urna, quis adipiscing nunc
                blandit non. Maecenas imperdiet ultricies dolor cursus accumsan at sem non lacus euismod aliquet
                in nec nisl.</p>
            <p>Donec dolor sapien, fringilla a congue id, congue nec enim. Nulla ultricies arcu et eros tempus
                in facilisis odio auctor. Duis nec dui ut metus elementum ullamcorper venenatis quis nunc. Ut
                interdum erat id purus varius luctus. Morbi nibh massa, vehicula eget eleifend ac, dapibus sed
                lacus. Donec imperdiet velit a tellus volutpat viverra. Donec id cursus mauris. Etiam vulputate
                fermentum consectetur. Integer id ipsum nec eros sollicitudin ornare faucibus feugiat nulla, id
                fringilla augue euismod et.</p>
        </article>
    </div>
</section>
</div>
<div class="body3">
    <div class="main">
        <section id="content2">
            <div class="line2 wrapper">
                <article class="col2 pad_right1">
                    <h3>Why Us</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tempor, justo sodales
                        fermentum consectetur, libero tellus fermentum sem, feugiat molestie orci enim sit amet
                        libero. Vivamus non velit in nibh tincidunt tristique tincidunt in leo. Phasellus eget nulla
                        odio. Maecenas at gravida lorem. Integer imperdiet euismod neque quis luctus. Donec
                        facilisis lobortis viverra. Quisque vehicula suscipit posuere. </p>
                    <ul class="list4 pad_bot2">
                        <li><a href="#">Nam non lacus dui, gravida condimentum tortor</a></li>
                        <li><a href="#">Maecenas ultrices volutpat euismod</a></li>
                        <li><a href="#">Nam pellentesque imperdiet urna, quis adipiscing nunc blandit non</a></li>
                        <li><a href="#">Maecenas imperdiet ultricies dolor cursus accumsan</a></li>
                        <li><a href="#">In at sem non lacus euismod aliquet in nec nisl</a></li>
                    </ul>
                    <p class="pad_bot1">Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere
                        cubilia Curae; Praesent sodales gravida accumsan. Nam nec urna in leo aliquam pharetra.
                        Fusce dapibus, mauris et aliquet eleifend, arcu dui placerat nisl, et ultricies lectus odio
                        nec neque. Aenean quam purus, adipiscing sit amet eleifend eu, consectetur ut tellus.</p>
                </article>
                <article class="col1">
                    <h3>Testimonials</h3>
                    <p class="pad_bot1"><strong class="color3">William Horner</strong><br><a href="#">Managing
                            Director</a><br>Company Name</p>
                    <p>Nam libero tempore, cum soluta nohbis esteligendi optio cumque nihil impedit quo minusid quod
                        maxime placeat facere possimus.</p>
                    <p class="pad_bot1"><strong class="color3">William Horner</strong><br><a href="#">Managing
                            Director</a><br>Company Name</p>
                    <p class="pad_bot1">Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus
                        saepe eveniet ut et voluptates repudiandae sint et molestiae non.</p>
                </article>
            </div>
        </section>


        <section id="content">
            <div class="wrapper">
                <article class="col3">
                    <h3>A Few Words About Us</h3>
                    <figure class="left marg_right1"><img src="images/page4_img1.jpg" alt=""></figure>
                    <p>Vivamus non velit in nibh tincidunt tristique tincidunt in leo. Phasellus eget nulla odio.
                        Maecenas at gravida lorem. Integer imperdiet euismod neque quis luctus. Donec facilisis lobortis
                        viverra. Quisque vehicula suscipit posuere. Nam non lacus dui, gravida condimentum tortor.
                        Maecenas ultrices volutpat euismod. Nam pellentesque imperdiet urna, quis adipiscing nunc
                        blandit non. Maecenas imperdiet ultricies dolor cursus accumsan at sem non lacus euismod aliquet
                        in nec nisl.</p>
                    <p>Donec dolor sapien, fringilla a congue id, congue nec enim. Nulla ultricies arcu et eros tempus
                        in facilisis odio auctor. Duis nec dui ut metus elementum ullamcorper venenatis quis nunc. Ut
                        interdum erat id purus varius luctus. Morbi nibh massa, vehicula eget eleifend ac, dapibus sed
                        lacus. Donec imperdiet velit a tellus volutpat viverra. Donec id cursus mauris. Etiam vulputate
                        fermentum consectetur. Integer id ipsum nec eros sollicitudin ornare faucibus feugiat nulla, id
                        fringilla augue euismod et.</p>
                </article>
            </div>
        </section>
    </div>
    <div class="body3">
        <div class="main">
            <section id="content2">
                <div class="line2 wrapper">
                    <article class="col2 pad_right1">
                        <h3>Why Us</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tempor, justo sodales
                            fermentum consectetur, libero tellus fermentum sem, feugiat molestie orci enim sit amet
                            libero. Vivamus non velit in nibh tincidunt tristique tincidunt in leo. Phasellus eget nulla
                            odio. Maecenas at gravida lorem. Integer imperdiet euismod neque quis luctus. Donec
                            facilisis lobortis viverra. Quisque vehicula suscipit posuere. </p>
                        <ul class="list4 pad_bot2">
                            <li><a href="#">Nam non lacus dui, gravida condimentum tortor</a></li>
                            <li><a href="#">Maecenas ultrices volutpat euismod</a></li>
                            <li><a href="#">Nam pellentesque imperdiet urna, quis adipiscing nunc blandit non</a></li>
                            <li><a href="#">Maecenas imperdiet ultricies dolor cursus accumsan</a></li>
                            <li><a href="#">In at sem non lacus euismod aliquet in nec nisl</a></li>
                        </ul>
                        <p class="pad_bot1">Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere
                            cubilia Curae; Praesent sodales gravida accumsan. Nam nec urna in leo aliquam pharetra.
                            Fusce dapibus, mauris et aliquet eleifend, arcu dui placerat nisl, et ultricies lectus odio
                            nec neque. Aenean quam purus, adipiscing sit amet eleifend eu, consectetur ut tellus.</p>
                    </article>
                    <article class="col1">
                        <h3>Testimonials</h3>
                        <p class="pad_bot1"><strong class="color3">William Horner</strong><br><a href="#">Managing
                                Director</a><br>Company Name</p>
                        <p>Nam libero tempore, cum soluta nohbis esteligendi optio cumque nihil impedit quo minusid quod
                            maxime placeat facere possimus.</p>
                        <p class="pad_bot1"><strong class="color3">William Horner</strong><br><a href="#">Managing
                                Director</a><br>Company Name</p>
                        <p class="pad_bot1">Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus
                            saepe eveniet ut et voluptates repudiandae sint et molestiae non.</p>
                    </article>
                </div>
            </section>






            piezas-----------------------------------
            <!-- <section id="content">
			<div class="line1">
				<div class="line2">
					<div class="line3 wrapper">
						<article class="col1">
							<article class="col2">
								<h3>Hosting Plans</h3>
								<ul class="list2">
									<li><img src="images/icon_1.png" alt="">Disk Space</li>
									<li><img src="images/icon_2.png" alt="">Monthly Data Transfer</li>
									<li><img src="images/icon_3.png" alt="">FTP Accounts</li>
									<li><img src="images/icon_4.png" alt="">Email Boxes</li>
									<li><img src="images/icon_5.png" alt="">Bandwidth Allowance</li>
									<li><img src="images/icon_6.png" alt="">Money Back Guarantee</li>
									<li><img src="images/icon_7.png" alt="">CGI, Ruby (RoR), Perl, PHP, MySQL</li>
									<li><img src="images/icon_8.png" alt="">Free Domains</li>
									<li><img src="images/icon_9.png" alt="">Free Site Builder</li>
									<li><img src="images/icon_10.png" alt="">MySQL Databases</li>
								</ul>
							</article>
							<article class="col3">
								<h3 class="color1">Small</h3>
								<ul class="list2">
									<li>300 GB</li>
									<li>3000 GB</li>
									<li>25</li>
									<li>1000</li>
									<li>Unlimited</li>
									<li>Anytime</li>
									<li><img src="images/marker_1.png" alt=""></li>
									<li>1</li>
									<li><img src="images/marker_1.png" alt=""></li>
									<li>Unlimited</li>
								</ul>
							</article>
							<article class="col3">
								<h3 class="color2">Medium</h3>
								<ul class="list2">
									<li>500 GB</li>
									<li>5000 GB</li>
									<li>50</li>
									<li>1000</li>
									<li>Unlimited</li>
									<li>Anytime</li>
									<li><img src="images/marker_2.png" alt=""></li>
									<li>1</li>
									<li><img src="images/marker_2.png" alt=""></li>
									<li>Unlimited</li>
								</ul>
							</article>
							<article class="col3">
								<h3 class="color4">Unlimited</h3>
								<ul class="list2">
									<li>Unlimited</li>
									<li>Unlimited</li>
									<li>Unlimited</li>
									<li>Unlimited</li>
									<li>Unlimited</li>
									<li>Anytime</li>
									<li><img src="images/marker_3.png" alt=""></li>
									<li>3</li>
									<li><img src="images/marker_3.png" alt=""></li>
									<li>Unlimited</li>
								</ul>
							</article>
						</article>
					</div>
				</div>
			</div>
		</section>
	</div>
	<div class="body3">
		<div class="main">
			<section id="content2">
				<div class="wrapper">
					<article class="col1">
						<article class="col2">
							<ul class="list3">
								<li><a href="#">Free Instant Setup</a></li>
								<li><a href="#">No Hidden Fees</a></li>
								<li><a href="#">Free Domain</a></li>
							</ul>
						</article>
						<article class="col3">
							<img src="images/price1.gif" alt="" class="pad_bot1">
							<a href="#" class="button1 color1">Sign Up Now</a>
						</article>
						<article class="col3">
							<img src="images/price2.gif" alt="" class="pad_bot1">
							<a href="#" class="button1 color2">Sign Up Now</a>
						</article>
						<article class="col3">
							<img src="images/price3.gif" alt="" class="pad_bot1">
							<a href="#" class="button1">Sign Up Now</a>
						</article>
					</article>
				</div>
			</section> -->






















            footer----------------------------------------------------------
            Website template designed by <a href="http://www.templatemonster.com/" target="_blank" rel="nofollow">www.templatemonster.com</a><br>
            3D Models provided by <a href="http://www.templates.com/product/3d-models/" target="_blank" rel="nofollow">www.templates.com</a>